### ISSUE TITLE
Where's the license?

### ISSUE THREAD

**Issue by marcospb19** [itepifanio/itepifanio.github.io#4]
Hey Itálo, can you please add a license so i can properly **_STEAL_** your content? :D
xD

**Comment by marcospb19** [comment]
Sou aquele cara do minicurso que indagou o uso do gráfico correto para o tipo de análise
Também o que perguntou se era Thanos o professor
Acho que assim você lembrará de mim

**Comment by itepifanio** [comment]
Olá, Marcos, acabei de adicionar a licença. Na real você acabou de me lembrar que tenho que dar os créditos a BlackrockDigital pelo [template](https://github.com/BlackrockDigital/startbootstrap-resume), só fiz adicionar o template ao Jekyll e modificar com meus dados

**Comment by marcospb19** [comment]
Obrigado!
